# Generated by Django 5.2.8 on 2025-11-16 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cnpj', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('chassi', models.CharField(max_length=100)),
                ('orimento', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('date_in', models.DateTimeField()),
                ('date_out', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=2000)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.client')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('position', models.CharField(max_length=100)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='funcionarios/')),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('datasheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='checklist.datasheet')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='checklist.worker')),
            ],
        ),
    ]
