# Generated by Django 5.2.8 on 2026-03-19 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('zip_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('pk', models.CompositePrimaryKey('client', 'address', blank=True, editable=False, primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_addresses', to='checklist.address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_addresses', to='checklist.client')),
            ],
            options={
                'db_table': 'client_addresses',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='clients', through='checklist.ClientAddress', to='checklist.address'),
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('pk', models.CompositePrimaryKey('employee', 'address', blank=True, editable=False, primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_addresses', to='checklist.address')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_addresses',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='employees', through='checklist.EmployeeAddress', to='checklist.address'),
        ),
        migrations.AddIndex(
            model_name='clientaddress',
            index=models.Index(fields=['client'], name='client_addr_client_idx'),
        ),
        migrations.AddIndex(
            model_name='clientaddress',
            index=models.Index(fields=['address'], name='client_addr_address_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeaddress',
            index=models.Index(fields=['employee'], name='employee_addr_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeaddress',
            index=models.Index(fields=['address'], name='employee_addr_address_idx'),
        ),
    ]
